from django.urls import path
from example_app import views

urlpatterns = [
    path("", views.root),
    path("health", views.health),
    path("basic/", views.basic_root),
    path("basic/ip", views.basic_ip),
    path("basic/health", views.basic_health),
    path("basic/echo", views.basic_echo),
    path("access/ip-whitelist", views.access_ip_whitelist),
    path("access/ip-blacklist", views.access_ip_blacklist),
    path("access/country-block", views.access_country_block),
    path("access/country-allow", views.access_country_allow),
    path("access/no-cloud", views.access_no_cloud),
    path("access/no-aws", views.access_no_aws),
    path("access/bypass-demo", views.access_bypass_demo),
    path("auth/https-only", views.auth_https_only),
    path("auth/bearer-auth", views.auth_bearer),
    path("auth/api-key", views.auth_api_key),
    path("auth/custom-headers", views.auth_custom_headers),
    path("rate/custom-limit", views.rate_custom_limit),
    path("rate/strict-limit", views.rate_strict_limit),
    path("rate/geo-rate-limit", views.rate_geo_limit),
    path("behavior/usage-monitor", views.behavior_usage_monitor),
    path(
        "behavior/return-monitor/<int:status_code>",
        views.behavior_return_monitor,
    ),
    path(
        "behavior/suspicious-frequency",
        views.behavior_suspicious_frequency,
    ),
    path("behavior/behavior-rules", views.behavior_rules),
    path("headers/", views.headers_root),
    path("headers/test-page", views.headers_test_page),
    path("headers/csp-report", views.headers_csp_report),
    path("headers/frame-test", views.headers_frame_test),
    path("headers/hsts-info", views.headers_hsts_info),
    path("headers/security-analysis", views.headers_security_analysis),
    path("content/no-bots", views.content_no_bots),
    path("content/json-only", views.content_json_only),
    path("content/size-limit", views.content_size_limit),
    path("content/referrer-check", views.content_referrer_check),
    path("content/custom-validation", views.content_custom_validation),
    path("advanced/business-hours", views.advanced_business_hours),
    path("advanced/weekend-only", views.advanced_weekend_only),
    path("advanced/honeypot", views.advanced_honeypot),
    path(
        "advanced/suspicious-patterns",
        views.advanced_suspicious_patterns,
    ),
    path("admin/unban-ip", views.admin_unban_ip),
    path("admin/stats", views.admin_stats),
    path("admin/clear-cache", views.admin_clear_cache),
    path("admin/emergency-mode", views.admin_emergency_mode),
    path("admin/cloud-status", views.admin_cloud_status),
    path("test/xss-test", views.test_xss),
    path("test/sql-injection", views.test_sql_injection),
    path(
        "test/path-traversal/<path:file_path>",
        views.test_path_traversal,
    ),
    path("test/command-injection", views.test_command_injection),
    path("test/mixed-attack", views.test_mixed_attack),
]
